version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: task_service_postgres # Added container_name
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
